<a href="https://colab.research.google.com/github/milkwasagoodchoice/Alice_books/blob/main/9_1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 9.1

> Replace all TODOs with your code. Do not change any other code.

In [2]:
# Do not edit this cell

import numpy as np
import pandas as pd

## Numpy

### Task 1

Create a 1D numpy array with elements [1, 2, 3, 4, 5]. Do it in two different ways.


In [3]:
res = np.array([1, 2, 3, 4, 5])

print(res)

[1 2 3 4 5]


In [5]:
res2 = np.arange(1, 6)

print(res2)

[1 2 3 4 5]


### Task 2

Create a 2D numpy array with shape (3, 5) filled with random integers between 1 and 100.

In [7]:
res3 = np.random.randint(1, 101, size=(3, 5))

print(res3)

[[50 48 29 87 67]
 [22  9 29  5 50]
 [11 22 18 97 39]]


### Task 3

Print the first row of array `res3`.

In [ ]:
print(array_2d[0])

### Task 4

Access the last column of array `res3`. Assume that the array may be of any 2D shape.

In [8]:
last_column = array_2d[:, -1]
print(last_column)

NameError: name 'array_2d' is not defined

### Task 5

Find the min, max, and sum of elements of the second column of array `res3`.

In [10]:
# Min
res_min = np.min(res3)

print('min =', res_min)

min = 5


In [ ]:
# Max
res_max = np.max(res)

print('max =', res_max)

In [ ]:
# Sum
res_max = np.sum(res)

print('sum =', res_max)

### Task 6

Tabulate the function

$$f(x) = e^{2x}$$

on interval `[0, 1]` with step 0.1.

By "tabulate" we mean that we want to have a table (1D array), where on the first position we will have the function value for 0, on the second position 0.1, and so on.

In [11]:
def f(x):
    return np.exp(2 * x)


x_values = np.arange(0, 1.1, 0.1)

f_values = f(x_values)

print(f_values)

[1.         1.22140276 1.4918247  1.8221188  2.22554093 2.71828183
 3.32011692 4.05519997 4.95303242 6.04964746 7.3890561 ]


## Pandas

We will be working on the classic dataset for beginner data scientists: Titanic passengers.

### Task 7

Load the dataset from the following URL: https://web.stanford.edu/class/cs102/datasets/Titanic.csv

In [ ]:
url = "https://web.stanford.edu/class/cs102/datasets/Titanic.csv"
df = pd.read_csv(url)

print(df.head())

### Task 8

Let's see the series/columns present in the data frame.

Also, let's inspect the first ten rows of data.

In [ ]:
print("Columns in the DataFrame:", df.columns)


In [ ]:
print("\nFirst ten rows of the DataFrame:")
print(df.head(10))

### Task 9

Add a new column - full name - it should be a concat of the first and last name.

In [ ]:
df['full name'] = df['First Name'] + ' ' + df['Last Name']

print(df[['First Name', 'Last Name', 'full name']].head())

### Task 10

Remove the two original columns - last, first.

In [ ]:
df = df.drop(columns=['First Name', 'Last Name'])

print(df.head())

### Task 11

Calculate the total number of survivors in the dataset.

In [ ]:
df_survivors = df[df['Survived'] == 1]

num_survivors = len(df_survivors)

print("Total number of survivors:", num_survivors)